// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVZV_MKuiARz_yAiEs9IgswZ3wp_YNvRw',
    appId: '1:21448281203:web:2f9c433875ff17b399ee06',
    messagingSenderId: '21448281203',
    projectId: 'sarriride-9c8d1',
    authDomain: 'sarriride-9c8d1.firebaseapp.com',
    storageBucket: 'sarriride-9c8d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ5rnWUf1u4MAqMYxnqI6Rt172TrAvZHk',
    appId: '1:21448281203:android:17ebba92b036164499ee06',
    messagingSenderId: '21448281203',
    projectId: 'sarriride-9c8d1',
    storageBucket: 'sarriride-9c8d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHjrwKL4YABrtSB2OBWAUCfmp4rNdJO-Y',
    appId: '1:21448281203:ios:6db747b9a76cfae899ee06',
    messagingSenderId: '21448281203',
    projectId: 'sarriride-9c8d1',
    storageBucket: 'sarriride-9c8d1.firebasestorage.app',
    iosClientId: '21448281203-h3pdin61q71kfvg79q6e5e0mj7umg7nk.apps.googleusercontent.com',
    iosBundleId: 'com.example.sarriRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHjrwKL4YABrtSB2OBWAUCfmp4rNdJO-Y',
    appId: '1:21448281203:ios:6db747b9a76cfae899ee06',
    messagingSenderId: '21448281203',
    projectId: 'sarriride-9c8d1',
    storageBucket: 'sarriride-9c8d1.firebasestorage.app',
    iosClientId: '21448281203-h3pdin61q71kfvg79q6e5e0mj7umg7nk.apps.googleusercontent.com',
    iosBundleId: 'com.example.sarriRide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVZV_MKuiARz_yAiEs9IgswZ3wp_YNvRw',
    appId: '1:21448281203:web:14e78615efd6d16699ee06',
    messagingSenderId: '21448281203',
    projectId: 'sarriride-9c8d1',
    authDomain: 'sarriride-9c8d1.firebaseapp.com',
    storageBucket: 'sarriride-9c8d1.firebasestorage.app',
  );
}
